# GitHub Action untuk membuat kontribusi dalam bentuk ular yang memakan commit.
name: Generate Snake

# Menjadwalkan workflow ini setiap 6 jam
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake
      - name: Generate Snake Contribution Graph
        uses: Platane/snk@v3  # Upgrade ke versi terbaru
        with:
          github_user_name: notfirsttt
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Tampilkan status Git
      - name: Show git status
        run: git status

      # Push hasil generate ke branch output
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Deploy hasilnya ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
